[package]
name = "dfstimizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
rand = "0.8.5"
num-bigint = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
